CREATE TABLE KEY_MAPPING(
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    MAPPING CHAR(1) NOT NULL
);

CREATE TABLE WUMA(
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    WUMA CHAR(5) NOT NULL
);
